# Generated by Django 2.1.7 on 2019-06-14 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2019, 6, 14, 11, 41, 51, 551607)),
        ),
    ]
