# Generated by Django 2.1.7 on 2019-06-14 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190614_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 6, 14, 18, 28, 57, 686130)),
        ),
    ]
